SBM:
  n_samples: 1000000
  sigma: 0.1
  sigma_begin: 0.001 # 初期時刻 σ_0
  sigma_end: 1.0 # 終端時刻 σ_T（固定値）
  n_steps: 200 # 拡散過程の分割ステップ数

sampling:  # ランジュバンサンプリング
  n_samples: 100000  # SBMサンプリングを動かすときのサンプル数
  alpha: 0.1
  n_steps: 200

model:
  n_channels: 2
  n_hidden: 2
  h_dim: 32

training:
  batch_size: 512  # バッチサイズ
  n_steps: 100000  # スコアモデルの訓練ステップ数
  log_step: 1000  # lossを何stepおきにレポートするか
  optim:
    optimizer:  # 最適化アルゴリズム
      name: Adam
      params:  # 最適化アルゴリズムに応じて項目を追加したり減らしたりする
        lr: 0.0001  # 学習率
        betas: [0.9, 0.999]
        eps: 1e-08
        weight_decay: 0
    lr_scheduler:  # 学習率調整アルゴリズム
      name: OneCycleLR
      params:
        max_lr: 0.001
        total_steps: 100000
  use_scheduler: True  # 学習率スケジューリングを使うか否か
